[global]
repo1-path=/backup/pgbackrest

repo1-retention-full=6
repo1-retention-diff=35
repo1-retention-archive=6
repo1-retention-archive-type=full

log-level-console=info
log-level-file=detail

start-fast=y

[mystanza]
pg1-path=/var/lib/postgresql/18/docker
pg1-port=5432
